// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvP5S8lhLsauc73BaNvYHM8S76y571RlI',
    appId: '1:385428964429:web:6b4ba0d888e89e397dc804',
    messagingSenderId: '385428964429',
    projectId: 'barbershop-171a1',
    authDomain: 'barbershop-171a1.firebaseapp.com',
    storageBucket: 'barbershop-171a1.firebasestorage.app',
    measurementId: 'G-0JEHVL1QST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWHZC4UmflwcPFXVvYQf2AC_fInbCSRcE',
    appId: '1:385428964429:android:10c082324b5ff2587dc804',
    messagingSenderId: '385428964429',
    projectId: 'barbershop-171a1',
    storageBucket: 'barbershop-171a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkch0-tujh6UO0xmVxDUU9eF1K-xmUSb8',
    appId: '1:385428964429:ios:cea0fbe6e4b8fa0d7dc804',
    messagingSenderId: '385428964429',
    projectId: 'barbershop-171a1',
    storageBucket: 'barbershop-171a1.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );
}
